export const APPLICATION_READY = "APPLICATION_READY";
export const API_REQUEST = "API_REQUEST";
export const LOAD_ASYNC_FILES = "LOAD_ASYNC_FILES";
export const BACK_TO_MAIN_PAGE = "BACK_TO_MAIN_PAGE";
export const BACK_TO_FILM_PAGE = "BACK_TO_FILM_PAGE";
